apiVersion: v1
kind: Service
metadata:
  name: rickapp-service
spec:
  selector:
    app: rickapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
    nodePort: 31111

